// <auto-generated />
namespace Exercise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddAcountType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAcountType));
        
        string IMigrationMetadata.Id
        {
            get { return "201901240436370_AddAcountType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
